### ISSUE TITLE
Unsable wave file

### ISSUE THREAD

**Issue by pnmpt** [Portugal-vAcc/messagemaker#51]
On this Aits sample [LPPT ATIS] [Q] 2100 [EXP ILS APCH] [RWY IN USE 03] [TL] 50 [FOR DEP CLEARANCE CONTACT TWR 118.100] [AFTER LANDING VACATE VIA HN] [WND] 330 [DEG] 8 [KT] [CAVOK] [TEMP] 9 [DP] 4 [QNH] 1029 [COMPLY WITH SPEED LIMITATIONS UNLESS OTHERWISE ADVISED BY ATC] [ACK LPPT INFO] [Q]
and respective URL send to server: https://messagemaker.herokuapp.com/?metar=LPPT%20122100Z%2033008KT%20CAVOK%2009/04%20Q1029&rwy=03&letter=Q

Euroscope reported "Error: Unusable WAVE file (not signed 16 bits 7350Hz mono)"
It does not say what is the file with this limitation

**Comment by pnmpt** [comment]
Its the File with Q "Quebec" with this issue

**Comment by pedro2555** [comment]
Make sure to delete all audio files, and replaced with the ones provided [latest release](https://github.com/Portugal-vAcc/messagemaker/releases/tag/1.8) package.zip

All audio files available on the releases tab are converted at push time by the [continuous integration server](https://github.com/Portugal-vAcc/messagemaker/blob/master/.travis.yml#L14) using [sox](http://sox.sourceforge.net/).
